package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
)

const (
	defaultInitClient       = ""
	defaultInitDataDir      = "data"
	defaultInitQuantCommand = "quant"
	initDirMode             = 0755
	initFileMode            = 0644
)

var (
	errInitUsage         = errors.New("init usage")
	errInitUnsupported   = errors.New("unsupported init client")
	errInitSkillSupport  = errors.New("project skills are not supported for this client in quant init")
	initIsInteractive    = isInteractiveInput
	initPrompt           = prompt
	supportedInitClients = []string{"opencode", "codex", "claude", "cursor", "copilot", "gemini"}
)

type initOptions struct {
	Client       string
	ProjectDir   string
	DataDir      string
	QuantCommand string
	Force        bool
	NoAgents     bool
	Skill        bool
	Autoupdate   bool
	ExplicitDir  bool
}

type initResult struct {
	Created []string
	Skipped []string
}

func runInitCommand(args []string) int {
	opts, err := parseInitArgs(args)
	if err != nil {
		if errors.Is(err, flag.ErrHelp) {
			printInitUsage()
			return 0
		}
		if errors.Is(err, errInitUnsupported) {
			fmt.Fprintf(os.Stderr, "error: unsupported client %q\n", opts.Client)
			fmt.Fprintf(os.Stderr, "supported clients: %s\n", strings.Join(supportedInitClients, ", "))
			return 1
		}
		if errors.Is(err, errInitUsage) {
			fmt.Fprintln(os.Stderr, "error:", err)
			fmt.Fprintln(os.Stderr)
			printInitUsage()
			return 1
		}
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}

	res, err := initProject(opts)
	if err != nil {
		if errors.Is(err, errInitSkillSupport) {
			fmt.Fprintln(os.Stderr, "error:", err)
			return 1
		}
		if errors.Is(err, errInitUnsupported) {
			fmt.Fprintf(os.Stderr, "error: unsupported client %q\n", opts.Client)
			fmt.Fprintf(os.Stderr, "supported clients: %s\n", strings.Join(supportedInitClients, ", "))
			return 1
		}
		fmt.Fprintln(os.Stderr, "error:", err)
		return 1
	}

	fmt.Printf("Initialized quant project for %s in %s\n", opts.Client, opts.ProjectDir)
	for _, path := range res.Created {
		fmt.Printf("created %s\n", path)
	}
	for _, path := range res.Skipped {
		fmt.Printf("skipped %s (already exists)\n", path)
	}
	return 0
}

func parseInitArgs(args []string) (initOptions, error) {
	opts := initOptions{
		Client:       defaultInitClient,
		ProjectDir:   ".",
		DataDir:      defaultInitDataDir,
		QuantCommand: defaultInitQuantCommand,
		Autoupdate:   true,
	}

	flagSet := flag.NewFlagSet("quant init", flag.ContinueOnError)
	flagSet.SetOutput(new(bytes.Buffer))
	flagSet.StringVar(&opts.ProjectDir, "dir", opts.ProjectDir, "Project root to initialize")
	flagSet.StringVar(&opts.DataDir, "data-dir", opts.DataDir, "Source document folder within the project")
	flagSet.StringVar(&opts.QuantCommand, "quant-command", opts.QuantCommand, "Command used in generated MCP configs")
	flagSet.BoolVar(&opts.Force, "force", opts.Force, "Overwrite files generated by quant init")
	flagSet.BoolVar(&opts.NoAgents, "no-agents", opts.NoAgents, "Do not create AGENTS.md or client instruction shims")
	flagSet.BoolVar(&opts.Skill, "skill", opts.Skill, "Also create a project skill when the selected client supports project skills")
	flagSet.BoolVar(&opts.Autoupdate, "autoupdate", opts.Autoupdate, "Include QUANT_AUTOUPDATE=true in generated MCP config")

	clientArg := ""
	parseArgs := args
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		clientArg = args[0]
		parseArgs = args[1:]
	}

	if err := flagSet.Parse(parseArgs); err != nil {
		return opts, err
	}

	flagSet.Visit(func(f *flag.Flag) {
		if f.Name == "dir" {
			opts.ExplicitDir = true
		}
	})

	remaining := flagSet.Args()
	if clientArg != "" {
		if len(remaining) > 0 {
			return opts, fmt.Errorf("%w: expected at most one client argument", errInitUsage)
		}
		opts.Client = strings.ToLower(strings.TrimSpace(clientArg))
	} else {
		switch len(remaining) {
		case 0:
			client, err := promptInitClient()
			if err != nil {
				return opts, err
			}
			opts.Client = client
		case 1:
			opts.Client = strings.ToLower(strings.TrimSpace(remaining[0]))
		default:
			return opts, fmt.Errorf("%w: expected at most one client argument", errInitUsage)
		}
	}

	if err := normalizeInitOptions(&opts); err != nil {
		return opts, err
	}
	return opts, nil
}

func promptInitClient() (string, error) {
	if !initIsInteractive() {
		return "", fmt.Errorf("%w: client is required in non-interactive mode", errInitUsage)
	}
	fmt.Printf("Supported clients: %s\n", strings.Join(supportedInitClients, ", "))
	answer, err := initPrompt(bufio.NewReader(os.Stdin), "Client: ")
	if err != nil {
		return "", err
	}
	return strings.ToLower(strings.TrimSpace(answer)), nil
}

func normalizeInitOptions(opts *initOptions) error {
	if !isSupportedInitClient(opts.Client) {
		return fmt.Errorf("%w", errInitUnsupported)
	}

	projectDir, err := filepath.Abs(opts.ProjectDir)
	if err != nil {
		return fmt.Errorf("resolving project dir: %w", err)
	}
	opts.ProjectDir = filepath.Clean(projectDir)

	dataDir := filepath.Clean(strings.TrimSpace(opts.DataDir))
	if dataDir == "" || dataDir == "." {
		return fmt.Errorf("data-dir must name a directory within the project")
	}
	if filepath.IsAbs(dataDir) {
		return fmt.Errorf("data-dir must be relative to the project")
	}
	for part := range strings.SplitSeq(dataDir, string(os.PathSeparator)) {
		if part == ".." {
			return fmt.Errorf("data-dir must stay within the project")
		}
	}
	opts.DataDir = filepath.ToSlash(dataDir)

	if len(commandParts(opts.QuantCommand)) == 0 {
		return fmt.Errorf("quant-command must not be empty")
	}
	return nil
}

func isSupportedInitClient(client string) bool {
	return slices.Contains(supportedInitClients, client)
}

func initProject(opts initOptions) (initResult, error) {
	var res initResult
	if !isSupportedInitClient(opts.Client) {
		return res, errInitUnsupported
	}
	if opts.Skill && opts.Client != "codex" && opts.Client != "claude" {
		return res, errInitSkillSupport
	}

	if err := os.MkdirAll(opts.ProjectDir, initDirMode); err != nil {
		return res, fmt.Errorf("creating project dir: %w", err)
	}

	dataDirPath := filepath.Join(opts.ProjectDir, filepath.FromSlash(opts.DataDir))
	if err := os.MkdirAll(dataDirPath, initDirMode); err != nil {
		return res, fmt.Errorf("creating data dir: %w", err)
	}
	res.Created = append(res.Created, displayInitPath(opts.ProjectDir, dataDirPath))

	if opts.ExplicitDir {
		wrote, err := writeGitignore(opts)
		if err != nil {
			return res, fmt.Errorf("writing .gitignore: %w", err)
		}
		gitignorePath := filepath.Join(opts.ProjectDir, ".gitignore")
		displayPath := displayInitPath(opts.ProjectDir, gitignorePath)
		if wrote {
			res.Created = append(res.Created, displayPath)
		} else {
			res.Skipped = append(res.Skipped, displayPath)
		}
	}

	files, err := renderInitFiles(opts)
	if err != nil {
		return res, err
	}
	for _, file := range files {
		wrote, err := writeInitFile(file.Path, file.Content, opts.Force)
		if err != nil {
			return res, err
		}
		displayPath := displayInitPath(opts.ProjectDir, file.Path)
		if wrote {
			res.Created = append(res.Created, displayPath)
		} else {
			res.Skipped = append(res.Skipped, displayPath)
		}
	}

	return res, nil
}

type initFile struct {
	Path    string
	Content []byte
}

func renderInitFiles(opts initOptions) ([]initFile, error) {
	files := []initFile{{
		Path:    filepath.Join(opts.ProjectDir, clientConfigPath(opts.Client)),
		Content: renderClientConfig(opts),
	}}

	if !opts.NoAgents {
		files = append(files, initFile{
			Path:    filepath.Join(opts.ProjectDir, "AGENTS.md"),
			Content: []byte(renderAgentsMD(opts)),
		})
		switch opts.Client {
		case "claude":
			files = append(files, initFile{
				Path:    filepath.Join(opts.ProjectDir, "CLAUDE.md"),
				Content: []byte("# Project Instructions\n\n@AGENTS.md\n"),
			})
		}
	}
	if opts.Client == "claude" {
		files = append(files, initFile{
			Path:    filepath.Join(opts.ProjectDir, ".claude", "settings.json"),
			Content: mustJSON(map[string]any{"permissions": map[string]any{"allow": []string{"mcp__quant__*"}}}),
		})
	}

	if opts.Skill {
		path := filepath.Join(opts.ProjectDir, ".agents", "skills", "quant-research", "SKILL.md")
		if opts.Client == "claude" {
			path = filepath.Join(opts.ProjectDir, ".claude", "skills", "quant-research", "SKILL.md")
		}
		files = append(files, initFile{
			Path:    path,
			Content: []byte(renderSkillMD(opts)),
		})
	}

	return files, nil
}

func clientConfigPath(client string) string {
	switch client {
	case "opencode":
		return "opencode.json"
	case "codex":
		return filepath.Join(".codex", "config.toml")
	case "claude":
		return ".mcp.json"
	case "cursor":
		return filepath.Join(".cursor", "mcp.json")
	case "copilot":
		return filepath.Join(".vscode", "mcp.json")
	case "gemini":
		return filepath.Join(".gemini", "settings.json")
	default:
		return ""
	}
}

func renderClientConfig(opts initOptions) []byte {
	switch opts.Client {
	case "opencode":
		return mustJSON(renderOpenCodeConfig(opts))
	case "codex":
		return []byte(renderCodexConfig(opts))
	case "claude":
		return mustJSON(map[string]any{"mcpServers": map[string]any{"quant": stdioServerConfig(opts, true)}})
	case "cursor":
		return mustJSON(map[string]any{"mcpServers": map[string]any{"quant": stdioServerConfig(opts, false)}})
	case "copilot":
		return mustJSON(map[string]any{"servers": map[string]any{"quant": stdioServerConfig(opts, true)}})
	case "gemini":
		cfg := map[string]any{"mcpServers": map[string]any{"quant": stdioServerConfig(opts, false)}}
		if !opts.NoAgents {
			cfg["contextFileName"] = "AGENTS.md"
		}
		return mustJSON(cfg)
	default:
		return nil
	}
}

func renderOpenCodeConfig(opts initOptions) map[string]any {
	quant := map[string]any{
		"type":    "local",
		"command": append(commandParts(opts.QuantCommand), "mcp", "--dir", dataDirArg(opts.DataDir)),
		"enabled": true,
	}
	if opts.Autoupdate {
		quant["env"] = map[string]string{"QUANT_AUTOUPDATE": "true"}
	}
	cfg := map[string]any{
		"$schema": "https://opencode.ai/config.json",
		"mcp":     map[string]any{"quant": quant},
		"permission": map[string]string{
			"quant_*": "allow",
		},
	}
	if !opts.NoAgents {
		cfg["instructions"] = []string{"AGENTS.md"}
	}
	return cfg
}

func stdioServerConfig(opts initOptions, includeType bool) map[string]any {
	parts := commandParts(opts.QuantCommand)
	cfg := map[string]any{
		"command": parts[0],
		"args":    append(parts[1:], "mcp", "--dir", dataDirArg(opts.DataDir)),
	}
	if includeType {
		cfg["type"] = "stdio"
	}
	if opts.Autoupdate {
		cfg["env"] = map[string]string{"QUANT_AUTOUPDATE": "true"}
	}
	return cfg
}

func renderCodexConfig(opts initOptions) string {
	parts := commandParts(opts.QuantCommand)
	args := append(parts[1:], "mcp", "--dir", dataDirArg(opts.DataDir))
	var b strings.Builder
	b.WriteString("[mcp_servers.quant]\n")
	b.WriteString("command = ")
	b.WriteString(strconv.Quote(parts[0]))
	b.WriteString("\n")
	b.WriteString("args = ")
	b.WriteString(tomlStringArray(args))
	b.WriteString("\n")
	if opts.Autoupdate {
		b.WriteString("\n[mcp_servers.quant.env]\n")
		b.WriteString("QUANT_AUTOUPDATE = \"true\"\n")
	}
	b.WriteString("\n[mcp_servers.quant.tools.\"*\"]\n")
	b.WriteString("approval_mode = \"approve\"\n")
	return b.String()
}

func renderAgentsMD(opts initOptions) string {
	dataDir := strings.TrimPrefix(dataDirArg(opts.DataDir), "./")
	return fmt.Sprintf(`# Research Assistant

## Data sources

Use the `+"`quant`"+` MCP tool to find information in the indexed documents.
Do not read files in the `+"`%s/`"+` folder directly - always search via MCP.

## How to answer

- When asked to research a topic, use MCP search before anything else.
- Do not search the internet unless explicitly asked.
- Do not speculate or assume - ground every claim in the source material.
- Always cite the specific document(s) used in your answer.
- If the search returns nothing relevant, say so rather than guessing.
`, dataDir)
}

func renderSkillMD(initOptions) string {
	return `---
name: quant-research
description: Use when researching source documents indexed by the quant MCP server.
---

# Quant Research

Use the ` + "`quant`" + ` MCP tool to search the indexed research documents before answering.
Do not read source files directly from the data folder.
Ground every claim in retrieved source material and cite the specific documents used.
If MCP search returns nothing relevant, say so instead of guessing.
`
}

func writeInitFile(path string, content []byte, force bool) (bool, error) {
	if err := os.MkdirAll(filepath.Dir(path), initDirMode); err != nil {
		return false, fmt.Errorf("creating parent directory for %s: %w", path, err)
	}
	if !force {
		if _, err := os.Stat(path); err == nil {
			return false, nil
		} else if !errors.Is(err, os.ErrNotExist) {
			return false, fmt.Errorf("checking %s: %w", path, err)
		}
	}
	if err := os.WriteFile(path, content, initFileMode); err != nil {
		return false, fmt.Errorf("writing %s: %w", path, err)
	}
	return true, nil
}

func renderGitignoreEntries(dataDir string) []string {
	return []string{
		dataDir + "/",
		"*quant.db",
		"*quant.db-*",
		".index/",
	}
}

func writeGitignore(opts initOptions) (bool, error) {
	gitignorePath := filepath.Join(opts.ProjectDir, ".gitignore")
	entries := renderGitignoreEntries(opts.DataDir)

	existing, err := os.ReadFile(gitignorePath) //nolint:gosec // path is built from opts.ProjectDir, not user input
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return false, fmt.Errorf("reading .gitignore: %w", err)
	}

	if errors.Is(err, os.ErrNotExist) {
		var b strings.Builder
		b.WriteString("# quant\n")
		for _, e := range entries {
			b.WriteString(e)
			b.WriteByte('\n')
		}
		if err := os.WriteFile(gitignorePath, []byte(b.String()), initFileMode); err != nil {
			return false, fmt.Errorf("writing .gitignore: %w", err)
		}
		return true, nil
	}

	lines := strings.Split(string(existing), "\n")
	existingSet := make(map[string]bool, len(lines))
	for _, line := range lines {
		existingSet[strings.TrimSpace(line)] = true
	}

	var newEntries []string
	for _, entry := range entries {
		if !existingSet[entry] {
			newEntries = append(newEntries, entry)
		}
	}
	if len(newEntries) == 0 {
		return false, nil
	}

	var b strings.Builder
	if len(existing) > 0 && existing[len(existing)-1] != '\n' {
		b.WriteByte('\n')
	}
	b.WriteString("# quant\n")
	for _, e := range newEntries {
		b.WriteString(e)
		b.WriteByte('\n')
	}

	f, err := os.OpenFile(gitignorePath, os.O_WRONLY|os.O_APPEND, initFileMode) //nolint:gosec // path is built from opts.ProjectDir, not user input
	if err != nil {
		return false, fmt.Errorf("opening .gitignore for append: %w", err)
	}
	defer func() { _ = f.Close() }()

	if _, err := f.WriteString(b.String()); err != nil {
		return false, fmt.Errorf("appending to .gitignore: %w", err)
	}
	return true, nil
}

func commandParts(command string) []string {
	return strings.Fields(strings.TrimSpace(command))
}

func dataDirArg(dataDir string) string {
	if strings.HasPrefix(dataDir, "./") {
		return dataDir
	}
	return "./" + dataDir
}

func tomlStringArray(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, strconv.Quote(value))
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

func mustJSON(v any) []byte {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		panic(err)
	}
	return append(data, '\n')
}

func displayInitPath(projectDir, path string) string {
	rel, err := filepath.Rel(projectDir, path)
	if err != nil || rel == "." {
		return filepath.ToSlash(path)
	}
	return filepath.ToSlash(rel)
}

func printInitUsage() {
	fmt.Println(`Usage:
  quant init [client] [flags]

Supported clients:
  opencode, codex, claude, cursor, copilot, gemini

Flags:
  --dir <path>              Project root to initialize (default ".")
  --data-dir <path>         Source document folder within the project (default "data")
  --quant-command <cmd>     Command used in generated MCP configs (default "quant")
  --force                   Overwrite files generated by quant init
  --no-agents               Do not create AGENTS.md or client instruction shims
  --skill                   Also create a project skill when supported by the selected client
  --autoupdate              Include QUANT_AUTOUPDATE=true in generated MCP config (default true)

Examples:
  quant init codex
  quant init opencode --dir ./my-research-project
  quant init codex --quant-command "go run ./cmd/quant"`)
}
